### Add these to Home Assistant if you don't have them already

#=========================
#=== Moon Phases
#=========================
- platform: moon

- platform: template
  sensors:
    #=========================
    #=== Sensors Info for Display
    #=========================
    weather_now:
      friendly_name: "Weather Now"
      value_template: >-
        {{ states.weather.home.state }};{{ states.weather.home.attributes.temperature | round(0) }}°F
    weather_fivedays:
      friendly_name: "Five day weather"
      value_template: >-
        {% for state in states.weather.home.attributes.forecast[0:3] -%}
          {{ as_timestamp(state.datetime)| timestamp_custom("%a") }};{{state.templow}}/{{ state.temperature }}°F;{{ state.condition }}#
        {%- endfor %}
    temperature_rooms:
      friendly_name: "Temperature Rooms"
      value_template: >-
        {{ states.sensor.garage_enviro_temperature.state }}°F;{{ states.sensor.living_room_temperature.state }}°F;{{ states.sensor.master_bedroom_temperature.state }}°F;{{ states.sensor.kaden_enviro_temperature.state }}°F;{{ states.sensor.master_bathroom_temperature.state }}°F;{{ states.sensor.guest_bath_temperature.state }}°F;{{ states.sensor.intake_temperature.state }}°F;{{ states.sensor.air_temperature.state }}°F;
    fl_weather:
      friendly_name: "Weather + Days"
      value_template: >-
        {{ now().strftime("%A") }};{{ states.sensor.weather_now.state }};{{ now().strftime("%B %-d") }};
